---
  collections:
    # Install a collection from Ansible Galaxy.
    - name: netbox.netbox
      version: '3.1.1'
    # Install juniper.device collection from Ansible Galaxy.
    - name: juniper.device
      version: '1.0.8'
    # Install junipernetworks collection from Ansible Galaxy.
    - name: junipernetworks.junos
      version: '10.0.0'
      
