---
  roles:
    # Install a role from Ansible Galaxy.
    - name: Juniper.junos
      version: '2.4.0'

  collections:
    # Install a collection from Ansible Galaxy.
    - name: netbox.netbox
      version: '3.1.1'
    # Install juniper.device collection from Ansible Galaxy.
    - name: juniper.device
      version: '1.0.1'
