---
- name: Creating common system config
  template: src=system.j2 dest={{ tmp_dir }}/system.cfg

- name: Creating management interface config
  template: src=management_interface.j2 dest={{ tmp_dir }}/management_interface.cfg

- name: Creating firewall port config
  template: src=firewall_port.j2 dest={{ tmp_dir }}/firewall_port.cfg

- name: Creating security config
  template: src=security.j2 dest={{ tmp_dir }}/security.cfg

- name: Creating lldp config
  template: src=lldp.j2 dest={{ tmp_dir }}/lldp.cfg

- name: Creating ospf config
  template: src=ospf.j2 dest={{ tmp_dir }}/ospf.cfg

- name: Creating fabric routing instance config
  template: src=fabric.j2 dest={{ tmp_dir }}/fabric.cfg

- name: Creating zones config
  template: src=zones.j2 dest={{ tmp_dir }}/zones.cfg

- name: Creating security policies config
  template: src=security_policies.j2 dest={{ tmp_dir }}/security_policies.cfg

