---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  nodeport_port: 31768
  web_replicas: 1
  task_replicas: 1
  projects_persistence: true
  projects_storage_size: 1Gi
  projects_existing_claim: awx-projects-claim
  postgres_data_volume_init: true
  postgres_storage_class: awx-postgres-volume
  postgres_init_container_commands: |
    chown 26:0 /var/lib/pgsql/data
    chmod 700 /var/lib/pgsql/data
