---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: awx-postgres-volume
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgress-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /var/lib/pgsql/data
