---
  collections:
    # Install a collection from Ansible Galaxy.
    - name: netbox.netbox
      version: '3.17.0'
    # Install juniper.device collection from Ansible Galaxy.
    - name: juniper.device
      version: '1.0.4'
    # Install junipernetworks collection from Ansible Galaxy.
    - name: junipernetworks.junos
      version: '5.3.1'
      
